# Generated by Django 4.0.5 on 2022-07-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price_address_zip_and_more'),
    ]

    operations = [
        migrations.RunSQL("""INSERT INTO store_collection(title) VALUES ('collection1')""", """
    DELETE FROM store_collection WHERE title='collection1  
    """)
    ]
